Repository OCA/intrastat-extrastat, pull requests merged in 2020-12, with the labels that each got.

#111 [13.0][FIX] Migration fixes + full migration scripts
  intrastat_product/migrations/13.0.1.0.3/post-migration.py
  intrastat_product/migrations/13.0.1.0.3/pre-migration.py
  intrastat_product/models/account_move.py
  intrastat_product/models/intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#112 [13.0][FIX] intrastat_product: migration script fix
  intrastat_product/migrations/13.0.1.0.3/post-migration.py
Labels: bot is merging ⏳

#113 [13.0]invoice_date -> date
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/readme/ROADMAP.rst
Labels: bot is merging ⏳, needs review

#114 [12.0][FIX] intrastat_product: date_invoice -> date
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳
