Repository OCA/intrastat-extrastat, pull requests merged in 2021-12, with the labels that each got.

#140 [14.0][IMP] product_harmonized_system_delivery: Make product.template#hs_code related
  product_harmonized_system_delivery/__init__.py
  product_harmonized_system_delivery/models/__init__.py
  product_harmonized_system_delivery/models/product.py
Labels: bot is merging ⏳, stale

#154 [14.0][FW] [13.0] product_harmonized_system: do not require company on…
  product_harmonized_system/models/hs_code.py
Labels: bot is merging ⏳

#156 [14.0][MIG] hs_code_id company_dependent=True to False
  product_harmonized_system/__manifest__.py
  product_harmonized_system/migrations/14.0.2.0.0/post-migration.py
  product_harmonized_system/models/product_category.py
  product_harmonized_system/models/product_template.py
Labels: approved

#141 [13.0][FIX]intrastat_product_declaration - fix amount by removing leg…
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳, stale

#162 [13.0]intrastat_product - fix amount_company_currency
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳

#161 [14.0][FIX]intrastat_product_declaration - fix amount by removing legacy currency conversion
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳
