Repository OCA/intrastat-extrastat, pull requests merged in 2022-05, with the labels that each got.

#172 [14.0]intrastat_product - remove incorrect domain on comutation line
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳

#170 [14.0][IMP] intrastat_product: Add read access to intrastat lines to …
  intrastat_product/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#164 [13.0]intrastat_product - fix read error on intrastat_line_ids
  intrastat_product/models/account_move.py
Labels: bot is merging ⏳

#173 [FIX] intrastat_product: fix error creating intrastat declaration
  intrastat_product/models/account_move.py
Labels: approved, bot is merging ⏳

#163 [14.0]intrastat Brexit support
  intrastat_base/models/__init__.py
  intrastat_base/models/res_partner.py
  intrastat_product/models/account_move.py
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/report/intrastat_product_report_xls.py
  intrastat_product/tests/__init__.py
  intrastat_product/tests/common.py
  intrastat_product/tests/test_brexit.py
  intrastat_product/views/account_move.xml
  intrastat_product/views/intrastat_product_declaration.xml
  product_harmonized_system/models/product_template.py
  product_harmonized_system/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#174 [14.0]fix intrastat brexit support
  intrastat_product/models/intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#157 [15.0][MIG] intrastat_base
  intrastat_base/README.rst
  intrastat_base/__init__.py
  intrastat_base/__manifest__.py
  intrastat_base/demo/intrastat_demo.xml
  intrastat_base/i18n/fr.po
  intrastat_base/i18n/intrastat_base.pot
  intrastat_base/models/__init__.py
  intrastat_base/models/account_chart_template.py
  intrastat_base/models/account_fiscal_position.py
  intrastat_base/models/account_fiscal_position_template.py
  intrastat_base/models/account_move.py
  intrastat_base/models/product_template.py
  intrastat_base/models/res_company.py
  intrastat_base/readme/CONTRIBUTORS.rst
  intrastat_base/readme/DESCRIPTION.rst
  intrastat_base/readme/INSTALL.rst
  intrastat_base/readme/USAGE.rst
  intrastat_base/static/description/icon.png
  intrastat_base/static/description/index.html
  intrastat_base/tests/__init__.py
  intrastat_base/tests/common.py
  intrastat_base/tests/models.py
  intrastat_base/tests/test_all.py
  intrastat_base/views/account_fiscal_position.xml
  intrastat_base/views/intrastat.xml
  intrastat_base/views/product_template.xml
  intrastat_base/views/res_config_settings.xml
  intrastat_base/views/res_partner.xml
  intrastat_base/wizards/__init__.py
  intrastat_base/wizards/res_config_settings.py
  setup/intrastat_base/odoo/addons/intrastat_base
  setup/intrastat_base/setup.py
Labels: approved, ready to merge, bot is merging ⏳
