Repository OCA/intrastat-extrastat, pull requests merged in 2023-11, with the labels that each got.

#235 [15.0][FIX] intrastat_product: intrastat declaration - restore _compute_numbers that was dropped by …
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳

#237 [16.0][FIX] intrastat_product: Prevent error when adding transaction details on invoices
  intrastat_product/models/account_move.py
Labels: bot is merging ⏳

#238 [16.0][IMP] intrastat_product: Set translate=True to description field from transactions
  intrastat_product/i18n/es.po
  intrastat_product/i18n/intrastat_product.pot
  intrastat_product/models/intrastat_transaction.py
Labels: approved, bot is merging ⏳

#232 [15.0][ADD] add new module intrastat_product_hscodes_import
  intrastat_product_hscodes_import/README.rst
  intrastat_product_hscodes_import/__init__.py
  intrastat_product_hscodes_import/__manifest__.py
  intrastat_product_hscodes_import/readme/CONTRIBUTORS.rst
  intrastat_product_hscodes_import/readme/DESCRIPTION.rst
  intrastat_product_hscodes_import/readme/USAGE.rst
  intrastat_product_hscodes_import/security/ir.model.access.csv
  intrastat_product_hscodes_import/static/data/2022_de_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_en_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_fr_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_nl_intrastat_codes.csv
  intrastat_product_hscodes_import/static/description/icon.png
  intrastat_product_hscodes_import/static/description/index.html
  intrastat_product_hscodes_import/static/description/installer_todo_example.png
  intrastat_product_hscodes_import/wizards/__init__.py
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer.py
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer_views.xml
  setup/intrastat_product_hscodes_import/odoo/addons/intrastat_product_hscodes_import
  setup/intrastat_product_hscodes_import/setup.py
Labels: bot is merging ⏳

#239 [IMP] intrastat_product_hscodes_import: improve error message
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer.py
Labels: needs review, bot is merging ⏳

#241 [IMP] intrastat_product_hscodes_import: simplify install wizard
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer.py
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer_views.xml
Labels: bot is merging ⏳

#230 [16.0] intrastat_product: use shipping partner instead of invoicing partner if any
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳

#244 [IMP] intrastat_product_hscodes_import: 2023 CN codes
  intrastat_product_hscodes_import/static/data/2022_de_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_en_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_fr_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2022_nl_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_de_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_en_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_fr_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_nl_intrastat_codes.csv
Labels: bot is merging ⏳

#240 [MIG] intrastat_product_hscodes_import: Migration to 16.0
  intrastat_product_hscodes_import/README.rst
  intrastat_product_hscodes_import/__init__.py
  intrastat_product_hscodes_import/__manifest__.py
  intrastat_product_hscodes_import/i18n/intrastat_product_hscodes_import.pot
  intrastat_product_hscodes_import/readme/CONTRIBUTORS.rst
  intrastat_product_hscodes_import/readme/DESCRIPTION.rst
  intrastat_product_hscodes_import/readme/USAGE.rst
  intrastat_product_hscodes_import/security/ir.model.access.csv
  intrastat_product_hscodes_import/static/data/2023_de_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_en_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_fr_intrastat_codes.csv
  intrastat_product_hscodes_import/static/data/2023_nl_intrastat_codes.csv
  intrastat_product_hscodes_import/static/description/icon.png
  intrastat_product_hscodes_import/static/description/index.html
  intrastat_product_hscodes_import/static/description/installer_todo_example.png
  intrastat_product_hscodes_import/wizards/__init__.py
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer.py
  intrastat_product_hscodes_import/wizards/intrastat_hscodes_import_installer_views.xml
  setup/intrastat_product_hscodes_import/odoo/addons/intrastat_product_hscodes_import
  setup/intrastat_product_hscodes_import/setup.py
Labels: bot is merging ⏳

#245 [IMP] intrastat_product - remove default company for intrastat regions
  intrastat_product/models/intrastat_region.py
Labels: approved, bot is merging ⏳

#242 [16.0] intrastat_product: suppl_unit_qty rounded to 1 if between 0 and 0.5
  intrastat_product/models/intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#246 [FIX] intrastat_product - set region_code based on code or the region
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/models/stock_warehouse.py
Labels: bot is merging ⏳

#248 [16.0][FIX] intrastat_product: Display note field as html on product declat…
  intrastat_product/views/intrastat_product_declaration.xml
Labels: bot is merging ⏳

#247 [16.0][IMP] intrastat_product: method for XLSX filename
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/report/report.xml
Labels: bot is merging ⏳

#249 [16.0][FIX] intrastat_product: Do not display missing VAT number error when…
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/tests/common.py
  intrastat_product/tests/common_sale.py
  intrastat_product/tests/test_sale_order.py
Labels: approved, ready to merge, bot is merging ⏳
