Repository OCA/intrastat-extrastat, pull requests merged in 2023-02, with the labels that each got.

#207 [16.0][MIG] product_harmonized_system
  product_harmonized_system/README.rst
  product_harmonized_system/__init__.py
  product_harmonized_system/__manifest__.py
  product_harmonized_system/demo/product_demo.xml
  product_harmonized_system/i18n/es.po
  product_harmonized_system/i18n/fr.po
  product_harmonized_system/i18n/hr.po
  product_harmonized_system/i18n/product_harmonized_system.pot
  product_harmonized_system/models/__init__.py
  product_harmonized_system/models/hs_code.py
  product_harmonized_system/models/product_category.py
  product_harmonized_system/models/product_product.py
  product_harmonized_system/models/product_template.py
  product_harmonized_system/readme/CONTRIBUTORS.rst
  product_harmonized_system/readme/DESCRIPTION.rst
  product_harmonized_system/readme/INSTALL.rst
  product_harmonized_system/readme/USAGE.rst
  product_harmonized_system/security/ir.model.access.csv
  product_harmonized_system/security/product_hs_security.xml
  product_harmonized_system/static/description/icon.png
  product_harmonized_system/static/description/index.html
  product_harmonized_system/views/hs_code.xml
  product_harmonized_system/views/product_category.xml
  product_harmonized_system/views/product_template.xml
  setup/product_harmonized_system/odoo/addons/product_harmonized_system
  setup/product_harmonized_system/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#209 [16.0][MIG] product_harmonized_system_delivery
  product_harmonized_system_delivery/README.rst
  product_harmonized_system_delivery/__init__.py
  product_harmonized_system_delivery/__manifest__.py
  product_harmonized_system_delivery/i18n/es.po
  product_harmonized_system_delivery/i18n/product_harmonized_system_delivery.pot
  product_harmonized_system_delivery/models/__init__.py
  product_harmonized_system_delivery/models/product_template.py
  product_harmonized_system_delivery/readme/CONTRIBUTORS.rst
  product_harmonized_system_delivery/readme/DESCRIPTION.rst
  product_harmonized_system_delivery/static/description/icon.png
  product_harmonized_system_delivery/static/description/index.html
  product_harmonized_system_delivery/views/product_template.xml
  setup/product_harmonized_system_delivery/odoo/addons/product_harmonized_system_delivery
  setup/product_harmonized_system_delivery/setup.py
Labels: bot is merging ⏳

#208 [16.0][MIG] product_harmonized_system_stock
  product_harmonized_system_stock/README.rst
  product_harmonized_system_stock/__init__.py
  product_harmonized_system_stock/__manifest__.py
  product_harmonized_system_stock/i18n/es.po
  product_harmonized_system_stock/i18n/product_harmonized_system_stock.pot
  product_harmonized_system_stock/readme/CONTRIBUTORS.rst
  product_harmonized_system_stock/readme/DESCRIPTION.rst
  product_harmonized_system_stock/static/description/icon.png
  product_harmonized_system_stock/static/description/index.html
  product_harmonized_system_stock/views/hs_code_menu.xml
  setup/product_harmonized_system_stock/odoo/addons/product_harmonized_system_stock
  setup/product_harmonized_system_stock/setup.py
Labels: bot is merging ⏳

#195 [FIX]intrastat declaration - weight is optional for hs codes with sup…
  intrastat_product/models/intrastat_product_declaration.py
Labels: bot is merging ⏳, stale

#205 [14.0][FIX] intrastat_product: Set the correct country code when the country of the delivery address is different (and to be consistent with the src_dest_country_id field).
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/tests/test_brexit.py
Labels: approved, bot is merging ⏳

#216 [15.0][FIX] intrastat_product: Set the correct country code when the country of the delivery address is different (and to be consistent with the src_dest_country_id field)
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/tests/test_brexit.py
Labels: approved, bot is merging ⏳
